version: '3'

services:
  server:
    image: server
    restart: on-failure
    build:
      context: ./server
      dockerfile: Dockerfile
    depends_on:
      - db
    environment:
      JWT_SECRET: restinpeace
      SUPER_ADMIN_EMAIL: admin@admin.com
      SUPER_ADMIN_PASSWORD: adminadmin
    ports:
      - '8000:8000'
    entrypoint: ['./wait.sh']
    volumes:
      - ./server:/app

  db:
    image: mysql
    command: --default-authentication-plugin=mysql_native_password
    restart: on-failure
    ports:
      - '33000:3306'
    environment:
      MYSQL_DATABASE: sellnbuy
      MYSQL_ROOT_PASSWORD: root
    volumes:
      - ./db:/docker-entrypoint-initdb.d/:ro

  client:
    build: ./client
    environment:
      NODE_PATH: src
    expose:
      - 3000
    ports:
      - 3000:3000
    volumes:
      - ./client/src:/app/src
    links:
      - server
    command: npm start
